### ISSUE TITLE
Possible to run tests using dart:io?

### ISSUE THREAD

**Issue by wstrange** [firebase/firebase-dart#105]
The README describes how to run tests for the firebase-dart package itself. 

Is it possible to write a test using dart:io instead of the browser?   (analogous to the java or node.js firebase server APIs)

**Comment by kevmoo** [comment]
When we're using the Firebase-provided JS API, we have to run in a browser – it assumes we're running in a browser.

We've discussed reimplementing this package using pure Dart (no wrapper) then one could use a lot more straight from the VM.

But as long as the code path you care about is using JS, you have to compile to JS and use a JS runtime.

Make sense?

**Comment by wstrange** [comment]
It makes sense. I just wish there was a pure Dart implementation ;-)

**Comment by kevmoo** [comment]
> It makes sense. I just wish there was a pure Dart implementation ;-)

Pull requests welcome 😜
