### ISSUE TITLE
Finish v4 API work

### ISSUE THREAD

**Issue by kevmoo** [firebase/firebase-dart#108]
https://firebase.google.com/support/release-notes/js#4.0.0

Making good progress on this branch: https://github.com/firebase/firebase-dart/tree/v4

@Janamou – if you're bored and want to run w/ this 😄  – just need to add the new APIs.

I think I have all of the removals done...

**Comment by Janamou** [comment]
Hi @kevmoo, sorry, I was out because of work. Is there still something I can do - e.g. the new APIs???

Thx

**Comment by kevmoo** [comment]
I'm going to publish v4 with a few missing things.

I'll make it a pull request soon.

I always love getting help finishing things up, though.

**Comment by kevmoo** [comment]
@Janamou - see https://github.com/firebase/firebase-dart/pull/112
