### ISSUE TITLE
DDC compatibility

### ISSUE THREAD

**Issue by dam0vm3nt** [firebase/firebase-dart#109]
Please it's possible to add a `@JS()` annotation to each `external` declaration in order to provide compatibility with `dartdevc` ?

**Comment by dam0vm3nt** [comment]
@kevmoo in the meanwhile I've sent a quick fix for firebase-dart.

**Comment by kevmoo** [comment]
@dam0vm3nt – we're golden now, right?

**Comment by kevmoo** [comment]
@dam0vm3nt – closing this. Feel free to reopen.

**Comment by dam0vm3nt** [comment]
@kevmoo lgtm, excuse me for late answer.

**Comment by kevmoo** [comment]
No worries at all. We're all busy. :-)
