### ISSUE TITLE
AuthCredential implementations missing

### ISSUE THREAD

**Issue by marcojakob** [firebase/firebase-dart#118]
The abstract class `AuthCredential` seems to have implementations in JavaScript but there are no corresponding subclasses in Dart. I would need something like the following to be able to access the GitHub `accessToken` in Dart:

```dart
@JS()
abstract class GithubAuthCredential extends AuthCredential{
  external String get accessToken;
}
```

I'm using the following code to get the access token:

```dart
    var provider = new fb.GithubAuthProvider();
    provider.addScope('repo');

    try {
      fb.UserCredential result = await _auth.signInWithPopup(provider);

      // User signed in successfully.
      _user = result.user;

      // This is the only place where we can access the Github token.
      _githubToken = (result.credential as GithubAuthCredential).accessToken;

      _fireSignedInChangedEvent();
    } catch (e) {
      print('Error authenticating with GitHub via Firebase: $e');
    }
  }
```

**Comment by Janamou** [comment]
@marcojakob Thanks for that, I will take a look.

**Comment by kevmoo** [comment]
@marcojakob I believe `AuthCredential` is meant to be opaque.

Looking at the JS API, I don't see anything exposed in the way you suggest - https://firebase.google.com/docs/reference/js/firebase.auth.AuthCredential

I know it's frustrating, but if we try to expose fields that aren't in the official JS API, we risk random breakage by exposing implementation details.

**Comment by marcojakob** [comment]
@kevmoo This is the only place I found to get hold of the **GitHub Access Token** (if you know some other way, please let me know). I need this to make API requests to the GitHub API.

It actually is mentioned in the JS API in the example of [GithubAuthProvider](https://firebase.google.com/docs/reference/js/firebase.auth.GithubAuthProvider). There is the following line:

```JavaScript
    // This gives you a GitHub Access Token.
    var token = result.credential.accessToken;
```

I think access to to the token at that point is clearly intended and needed. Maybe it is something that should be added to the JS API documentation. In [AuthCredential](https://firebase.google.com/docs/reference/js/firebase.auth.AuthCredential) there is a sentence that sais *Implementations specify the details* but these details cannot be found in the docs. I think they should be added to the Firebase docs.

**Comment by kevmoo** [comment]
@marcojakob – please file an issue here - https://github.com/firebase/firebase-js-sdk/issues/new

I'll see what I can learn internally...

**Comment by AlexandreRoba** [comment]
Hi all, Any update on this? We can see from the [JS SDK](https://firebase.google.com/docs/reference/js/firebase.auth.OAuthCredential.html) that the AuthCredential has extra "Optional" fields such as idTokens and accessToken... I need access to those after the identification in order to store them on my servers for further calls...

@kevmoo I will work on an implementation on this this, unless you see another way to get those idtokens and accesstokens?

thanks,
