### ISSUE TITLE
Give an option to specify email language?

### ISSUE THREAD

**Issue by kevmoo** [firebase/firebase-dart#127]
I LOVE this feature...and I don't want to be en-centric, but I think many folks may think it's broken to get Czech by default – where they're likely used to getting English.

https://github.com/firebase/firebase-dart/blob/a0e8fe3f0eb93432a4b157af1b461dcbc32d0f79/example/auth/index.dart#L69

Wondering if we could either:

- put in a drop-down
- detect the current browser language and send accordingly

**Comment by kevmoo** [comment]
CC @Janamou

**Comment by Janamou** [comment]
You are right @kevmoo. I added selectbox with 4 languages. You can check it here: #129

**Comment by kevmoo** [comment]
@Janamou – we can close this now, right?

**Comment by Janamou** [comment]
@kevmoo yep! thx

**Comment by kevmoo** [comment]
Fixed in https://github.com/firebase/firebase-dart/commit/3081927f43d2232f78899f82a21d402e2a4c6e6b
