### ISSUE TITLE
Unsupported operation: Platform._version

### ISSUE THREAD

**Issue by supermuka** [firebase/firebase-dart#132]
When I try the follow code:

´ 
   await fb.auth().signInWithEmailAndPassword(email, password);   
   var token = await fb.auth().currentUser.getToken();
   // HERE ERROR 
   var fc = new fb_io.FirebaseClient(token);
´

I get the this error:

´
VM44:1 EXCEPTION: 'dart:io-patch/platform_patch.dart': error: line 25: native function 'Platform_GetVersion' (0 arguments) cannot be found
  static String _version() native "Platform_GetVersion";
  ^

STACKTRACE: 
platform_impl.dart 110                                       _Platform.version
platform.dart 73                                             Platform._version
platform.dart 73                                             Platform._version
platform.dart 229                                            Platform.version
http_impl.dart 2843                                          _getHttpVersion
http_impl.dart 1672                                          new _HttpClient
http.dart 1338                                               new HttpClient
package:http/src/io_client.dart 23:56                        new IOClient
package:firebase/firebase_io.dart 21:33                      new FirebaseClient
package:preco_mi/src/entidade/entidade_component.dart 49:17  EntidadeComponent.ngOnInit
package:preco_mi/app_component.template.dart 950:31          _ViewAppComponent2.detectChangesInternal
package:angular/src/core/linker/app_view.dart 371:7          AppView.detectChanges
package:angular/src/debug/debug_app_view.dart 139:24         DebugAppView.detectChanges
package:angular/src/core/linker/view_container.dart 59:22    ViewContainer.detectChangesInNestedViews
package:preco_mi/app_component.template.dart 134:14          ViewAppComponent0.detectChangesInternal
package:angular/src/core/linker/app_view.dart 371:7          AppView.detectChanges
package:angular/src/debug/debug_app_view.dart 139:24         DebugAppView.detectChanges
package:preco_mi/app_component.template.dart 1838:17         _ViewAppComponentHost0.detectChangesInternal
package:angular/src/core/linker/app_view.dart 371:7          AppView.detectChanges
package:angular/src/debug/debug_app_view.dart 139:24         DebugAppView.detectChanges
package:angular/src/core/linker/view_ref.dart 104:13         ViewRefImpl.detectChanges
package:angular/src/core/application_ref.dart 441:30         ApplicationRefImpl._runTick
package:angular/src/core/application_ref.dart 421:7          ApplicationRefImpl.tick
package:angular/src/core/application_ref.dart 277:9          new ApplicationRefImpl.<fn>.<fn>
dart:async                                                   _ZoneDelegate.run
package:angular/src/core/zone/ng_zone.dart 175:21            NgZone._run
dart:async                                                   _CustomZone.runGuarded
package:angular/src/core/zone/ng_zone.dart 310:23            NgZone.runGuarded
package:angular/src/core/application_ref.dart 276:13         new ApplicationRefImpl.<fn>
dart:async                                                   _BroadcastStreamController.add
package:angular/src/core/zone/ng_zone.dart 267:55            NgZone._checkStable
package:angular/src/core/zone/ng_zone.dart 213:5             NgZone._onLeave
package:angular/src/core/zone/ng_zone.dart 177:7             NgZone._run

-----async gap-----
dart:async                                                  _Completer.completeError
package:preco_mi/src/entidade/entidade_component.dart 71:3  EntidadeComponent.ngOnInit

-----async gap-----
dart:async                                                   _asyncThenWrapperHelper
package:preco_mi/src/entidade/entidade_component.dart 40:20  EntidadeComponent.ngOnInit
package:preco_mi/app_component.template.dart 950:31          _ViewAppComponent2.detectChangesInternal
package:angular/src/core/linker/app_view.dart 371:7          AppView.detectChanges
package:angular/src/debug/debug_app_view.dart 139:24         DebugAppView.detectChanges
package:angular/src/core/linker/view_container.dart 59:22    ViewContainer.detectChangesInNestedViews
package:preco_mi/app_component.template.dart 134:14          ViewAppComponent0.detectChangesInternal
package:angular/src/core/linker/app_view.dart 371:7          AppView.detectChanges
package:angular/src/debug/debug_app_view.dart 139:24         DebugAppView.detectChanges
package:preco_mi/app_component.template.dart 1838:17         _ViewAppComponentHost0.detectChangesInternal
package:angular/src/core/linker/app_view.dart 371:7          AppView.detectChanges
package:angular/src/debug/debug_app_view.dart 139:24         DebugAppView.detectChanges
package:angular/src/core/linker/view_ref.dart 104:13         ViewRefImpl.detectChanges
package:angular/src/core/application_ref.dart 441:30         ApplicationRefImpl._runTick
package:angular/src/core/application_ref.dart 421:7          ApplicationRefImpl.tick
package:angular/src/core/application_ref.dart 277:9          new ApplicationRefImpl.<fn>.<fn>
dart:async                                                   _ZoneDelegate.run
package:angular/src/core/zone/ng_zone.dart 175:21            NgZone._run
dart:async                                                   _CustomZone.runGuarded
package:angular/src/core/zone/ng_zone.dart 310:23            NgZone.runGuarded
package:angular/src/core/application_ref.dart 276:13         new ApplicationRefImpl.<fn>
dart:async                                                   _BroadcastStreamController.add
package:angular/src/core/zone/ng_zone.dart 267:55            NgZone._checkStable
package:angular/src/core/zone/ng_zone.dart 213:5             NgZone._onLeave
package:angular/src/core/zone/ng_zone.dart 177:7             NgZone._run

ORIGINAL EXCEPTION: 'dart:io-patch/platform_patch.dart': error: line 25: native function 'Platform_GetVersion' (0 arguments) cannot be found
  static String _version() native "Platform_GetVersion";
  ^

´

**Comment by Janamou** [comment]
@supermuka I am not sure but I see you are using Angular. What I know is that you have to have the httpclient registered in bootstrap method. See here:
https://webdev.dartlang.org/angular/guide/server-communication

Or what do you think @kevmoo?

**Comment by supermuka** [comment]
Yes, I am using Angular. I added the httpclient in bootstrap method like you indicated, but the error continues...

**Comment by kevmoo** [comment]
Are you importing `firebase_io.dart`?

You cannot mix and match these.

**Comment by supermuka** [comment]
I am importing:

```
import 'package:firebase/firebase.dart' as fb;
import 'package:firebase/firebase_io.dart' as fb_io;
```

**Comment by kevmoo** [comment]
Yeah, we should be more clear here.

firebase.dart – browser only
firebase_io.dart - server only

**Comment by supermuka** [comment]
Understood. I would like to use CRUD (REST) functionality on browser side with Angular.  For example, when I need recovery data, I explicity call a method "GET". I don´t want that a "listen" is recovering data. Is there a way to do this on browser?

**Comment by kevmoo** [comment]
Good feature request – just need to ponder how to expose that...

**Comment by stevenroose** [comment]
I also get this. 

pubspec has 
```yaml

dependencies:
  http: ^0.11.3+16
  path: ^1.5.1
  angular: ^4.0.0
  angular_forms: ^1.0.0
  angular_components: ^0.8.0
  stream_transform: ^0.0.6
```
main has 
```dart 
void main() {
  bootstrap(AppComponent, [
    provide(Client, useFactory: () => new BrowserClient(), deps: []),
  ]);
}
```

I'm starting to get the feeling that Google doesn't really want anyone to use AngularDart...

**Comment by kevmoo** [comment]
@stevenroose – did you read our comment here https://github.com/firebase/firebase-dart/issues/132#issuecomment-334213232 ?

**Comment by stevenroose** [comment]
@kevmoo I don't use Firebase. Sorry to drop my issue in this thread, it's just the only resource I found for this issue :D 
I worked around this by not using the angular `provide()` thing, but just manually create a `BrowserClient` where I needed it. The DI doesn't seem to work very well.
