### ISSUE TITLE
Firestore support doesn't work with DDC

### ISSUE THREAD

**Issue by Blimster** [firebase/firebase-dart#136]
Calling `DocumentSnapshot.data()` in Chrome served by `pub serve --web-compiler=dartdevc` results to `CastError: Casting value of type 'JSObject<e>' to incompatible type 'JSObject<n>'`.

Steps to reproduce:
- Use Dart SDK 1.24.2
- Take the Firestore example and extend it with a call to `DocumentSnapshot.data()`
- Host the example with `pub serve --web-compiler=dartdevc`
- Open the example in Chrome.

**Comment by kevmoo** [comment]
@Blimster – will take a look!

**Comment by kevmoo** [comment]
@Blimster – could you create a branch of this repo w/ your change `extend it with a call to DocumentSnapshot.data()` – so I can see what your failure is?

**Comment by Blimster** [comment]
@kevmoo - i can reproduce the problem simply by using the example app in /example/firestore:

- Serve the example by using `pub serve --all --web-compiler=dartdevc`
- Open the example in Chrome with `http://localhost:8080/`.
- You will see the error in the Chrome console.

**Comment by kevmoo** [comment]
Are you using Dart 1.24?

**Comment by Blimster** [comment]
Yes, 1.24.3

**Comment by kevmoo** [comment]
I just tested with `2.0.0-dev.15.0` – it's possible there are bugs in DDC that have since been fixed.

If you'd like to use DDC here, you'll have to start using Dart v2 dev releases.
