### ISSUE TITLE
Firestore documents with fields of type reference don't work

### ISSUE THREAD

**Issue by Blimster** [firebase/firebase-dart#137]
Access to a Firestore document with a field of type `reference` results to `TypeError: Converting circular structure to JSON`.

Steps to reproduce:
- Dart SDK 1.24.2
- Create a Firestore documents with a reference to another document.
- Use the Firestore example and extend it with an access the the document using `DocumentSnapshot.data()`.
- Open the example in Dartium.

**Comment by Janamou** [comment]
@Blimster Thanks for the issue. Can you please share more about the structure of your data?
What I know is that in Firestore can be a collection of documents but document can't contain another document. It can contain only subcollection (see explanation here https://www.youtube.com/watch?time_continue=139&v=2Vf1D-rUMwE)

**Comment by kevmoo** [comment]
Yes, @Blimster – as I said in https://github.com/firebase/firebase-dart/issues/136 – it's be great to see the actual code you're running.

Also: please rebase your code on top of the latest master branch! Thanks!

**Comment by Blimster** [comment]
@Janamou - I know that a document can't store another document. But i think you can store a reference to another document. See Firestore datatype docs: https://firebase.google.com/docs/firestore/manage-data/data-types. the docs for the reference datatype are not very detailed. Some more informations are here: https://stackoverflow.com/questions/46568850/what-is-firestore-reference-data-type-good-for

@kevmoo - I can't provide a self contained example to reproduce the exception, because it is not supported to store a field of type reference (as discussed in the Stackoverflow thread, it is possible in the Javascript world). But you can do the following:

- Create a document using the Firesbase console in the collection `pkg_firestore` with the fields the example app requires (`createdAt` and `text`).
- Create another document and add a third field of datatype `reference` and enter the reference to the first document.
- Open the Firestore example and you will see the error in the Chrome console.

After I read the Stackoverflow discussion, i don't really understand the reason for the datatype `reference` and i think a good workaround is to store the path to a document just as a string. But there is this datatype and so it should be supported.

**Comment by kevmoo** [comment]
@Blimster – will take a look!
