### ISSUE TITLE
Firestore document with DateTime fields support

### ISSUE THREAD

**Issue by alextekartik** [firebase/firebase-dart#138]
Date is a supported type in Firestore, but I can't see any validation in the the tests on that. It seems that when compiled to JS, writing a DateTime simply failed and on Dartium DateTime fields are read as String. I extended the the following test (firestore_test.dart):

````
test("set various types", () async {
  var docRef = ref.doc("message4");

  var map = {
    "stringExample": "Hello world!",
    "booleanExample": true,
    "numberExample": 3.14159265,
    "arrayExample": [5, true, "hello"],
    "nullExample": null,
    "mapExample": {
      "a": 5,
      "b": {"nested": "foo"}
    },
    "dateTimeExample": new DateTime.fromMillisecondsSinceEpoch(123456789, isUtc: true)
  };

  await docRef.set(map);
  var snapshot = await docRef.get();
  var snapshotData = snapshot.data();

  expect(snapshotData["stringExample"], map["stringExample"]);
  expect(snapshotData["booleanExample"], map["booleanExample"]);
  expect(snapshotData["numberExample"], map["numberExample"]);
  expect(snapshotData["arrayExample"], map["arrayExample"]);
  expect(snapshotData["nullExample"], map["nullExample"]);
  expect(snapshotData["mapExample"], map["mapExample"]);
  expect(snapshotData["dateTimeExample"], map["dateTimeExample"]);
});
````

**Comment by alextekartik** [comment]
The issue seems to be jsify. And unfortunately the behavior is different on Chrome and Dartium. Since supporting DateTime was a must I found the ugliest workaround to support it (https://github.com/tekartik/firebase-dart/commit/a3683fdf66cc1a670f99766e5be23264aa27dd06). Somehow the DateTime field is not converted to a Date object when using dart2js...

**Comment by kevmoo** [comment]
Taking a look, @alextekartik !

**Comment by alextekartik** [comment]
Great, actually the issue could be extended to all the other types (https://firebase.google.com/docs/firestore/manage-data/data-types) that can easily be entered in the firestore database console. I wonder whether we really need to convert all data fields from JS to Dart (cost?); I could not find an easy way to ‘check’ the JS type of each field. Maybe having an opaque DocumentData where we could read/write fields and subfields (à la ContentValues on Android) could be a solution. 
An important date value to support when writing is `ServerValue.TIMESTAMP`
To note that there is a firestore node wrapper (https://github.com/pulyaevskiy/firestore-interop) that seems to get stuck at the exact same issue. Good luck!

**Comment by kevmoo** [comment]
> An important date value to support when writing is ServerValue.TIMESTAMP (the unit test checks that it is not null but not that it is actually a date!)

`ServerValue.TIMESTAMP` is actually meant to be opaque. The docs specify it's a placeholder - with a type of `Object` - https://firebase.google.com/docs/reference/js/firebase.database.ServerValue

I just updated a test to verify that other timestamps are round-tripped correctly - https://github.com/firebase/firebase-dart/pull/145/commits/09ba975bffb9010edaee40667c55fe25ddee1330#diff-d8e8e7a8baba8b38154bf828d4094587R328
