### ISSUE TITLE
Firestore package not recognized in sample app

### ISSUE THREAD

**Issue by dunmashiku** [firebase/firebase-dart#140]
@Janamou and everyone, 
Thank you for all the work you do for angular dart and firebase. @Janamou I was going to add add Firestore to your angulardart sample app: https://github.com/Janamou/firebase-demo-ng. 

Just wanted to ask how to resolve the issue with this package not being recognized: 
`import 'package:firebase/firebase_firestore.dart' as fs;`

Also updated pubspec with `firebase: "^4.2.0+1"`

I have added the two scripts: 
`<script src="https://www.gstatic.com/firebasejs/4.8.0/firebase.js"></script>
    <script src="https://www.gstatic.com/firebasejs/4.8.0/firebase-firestore.js"></script>`

Any help greatly appreciated,
Dun

**Comment by Janamou** [comment]
@dunmashiku Thank you for updating the sample app!
The "problem" is that the latest package version with Firestore is not yet on the pub.
So you need to install it from Github for now. In pubspec:

```
dependencies:
  firebase:
    git: git://github.com/firebase/firebase-dart.git
```

More info: https://www.dartlang.org/tools/pub/dependencies#git-packages

**Comment by kevmoo** [comment]
What @Janamou said 😄

**Comment by kevmoo** [comment]
@dunmashiku – 4.3 is out now! https://pub.dartlang.org/packages/firebase

**Comment by dunmashiku** [comment]
@Janamou @kevmoo Thank you. I will make the update and create a pull request to sample app: https://github.com/Janamou/firebase-demo-ng when I get a chance this coming weekend. Thank you again for your help!

**Comment by dunmashiku** [comment]
Still having issues getting Firestore to be recognized. I tried:

```
firebase:
    git: git://github.com/firebase/firebase-dart.git
```

The issue still remains on how to instantiate firestore. This does not work:

```
import 'package:firebase/firebase.dart';
import 'package:firebase/firestore.dart' as fs;

void main() {
  initializeApp(
    apiKey: "YourApiKey",
    authDomain: "YourAuthDomain",
    databaseURL: "YourDatabaseUrl",
    projectId: "YourProjectId",
    storageBucket: "YourStorageBucket");

  fs.Firestore firestore = firestore();
  fs.CollectionReference ref = firestore.collection("messages");

  ref.onSnapshot.listen((querySnapshot) {
    querySnapshot.docChanges.forEach((change) {
      if (change.type == "added") {
        // Do something with change.doc
      }     
    });
  });
}
```

Any advice greatly appreciated. 
Dun

**Comment by kevmoo** [comment]
@dunmashiku – you should be able to use the package straight off of the pub site.

Try that and let us know if you still have issues

**Comment by dunmashiku** [comment]
Thank you! @kevmoo

**Comment by kevmoo** [comment]
@dunmashiku – all fixed?

**Comment by dunmashiku** [comment]
@kevmoo Let me try it out tonight after work. I will let you know as soon as possible. Thank you again!

**Comment by dunmashiku** [comment]
@kevmoo All is fixed! Thank you!
