### ISSUE TITLE
Update to 4.10.x

### ISSUE THREAD

**Issue by kevmoo** [firebase/firebase-dart#149]
Some changes have landed: https://firebase.google.com/support/release-notes/js

CC @Janamou

**Comment by Janamou** [comment]
@kevmoo Can you assign me this issue? I can check the remaining stuff during the weekend...

**Comment by kevmoo** [comment]
Sadly, I cannot assign the issue to you. But consider it yours! 😄

**Comment by kevmoo** [comment]
Still missing:

isEqual: SnapshotMetadata, DocumentSnapshot, QuerySnapshot, CollectionReference
Firestore: connect/disconnect

And we have 4.10.x now...

**Comment by kevmoo** [comment]
I think we're good as of https://github.com/firebase/firebase-dart/commit/c1377eca74092948a6553ac9350a97de79b428c1

**Comment by kevmoo** [comment]
v4.5.0 is out w/ this commit - https://pub.dartlang.org/packages/firebase
