### ISSUE TITLE
Signin a second time timesout

### ISSUE THREAD

**Issue by sturmf** [firebase/firebase-dart#154]
I am writing some angular dart tests to check my firestore rules. Therefore within a single test I want to sign in with alice, do something, signout, signin with bob, check that bob has no access. Then sign out again and sign in with alice.

Unfortunately the second sign in with alice times out.
My signin helper looks like this:

```
Future<fb.User> signIn(fb.App app, String user, String password) async {
  if (app.auth().currentUser != null) {
    await app.auth().signOut();
  }
  return app.auth().signInWithEmailAndPassword(user, password);
}
```

The error message is:

```
  TimeoutException after 0:00:30.000000: Test timed out after 30 seconds.
  dart:html  _EventStreamSubscription._EventStreamSubscription.<fn>

```

**Comment by Janamou** [comment]
@sturmf have you tried to put await before the app.auth().signInWithEmailAndPassword?
Can you also show us the test?

**Comment by sturmf** [comment]
The await is in the test itself. Don't know where it would be better. The full test is here.

```
  test('Alice can make Bob an owner of a sailing club she is owner of but Bob cant', () async {
    fb.User alice = await signIn(_app, _config['USER']['ALICE']['EMAIL'], _config['USER']['ALICE']['PASSWORD']);
    final fs.CollectionReference _fsRefSailingClubs = _fbStore.collection("sailing_clubs");

    // Create
    final Map<String, dynamic> sailingClubMap = {'name': 'a test'};
    sailingClubMap['roles'] = {alice.uid: 'owner'};
    final sailingClub = await _fsRefSailingClubs.add(sailingClubMap);

    // Switch to Bob and try to make himself an owner
    final fb.User bob = await signIn(_app, _config['USER']['BOB']['EMAIL'], _config['USER']['BOB']['PASSWORD']);
    expect(sailingClub.set({"roles": {bob.uid: 'owner'}}, new fs.SetOptions(merge: true)),
        throwsToString(contains('Missing or insufficient permissions')));

    // Switch back to Alice and try to make Bob an owner
    alice = await signIn(_app, _config['USER']['ALICE']['EMAIL'], _config['USER']['ALICE']['PASSWORD']);
    // hangs above, the second sign in as alice times out
    await sailingClub.set({"roles": {bob.uid: 'owner'}}, new fs.SetOptions(merge: true));
    final snapshot = await sailingClub.get();
    expect(snapshot.data()['roles'][alice.uid], 'owner');
    expect(snapshot.data()['roles'][bob.uid], 'owner');
  });
```

**Comment by sturmf** [comment]
Ok one problem was using references as bob which were created under the user alice. But even after fixing this I still can't sign in a second time with alice if I produced an exception with bob. The exception is the intended test that bob can't elevate his privileges. So any idea what I have to do after the exception to continue and login as alice again?

```
expect(sailingClubBob.set({"roles": {bob.uid: 'owner'}}, new fs.SetOptions(merge: true)),
        throwsToString(contains('Missing or insufficient permissions')));
```
and the throwsToString is your matcher as from the tests.

```
Matcher throwsToString(dynamic value) => throwsA(new _ToStringMatcher(value));

class _ToStringMatcher extends CustomMatcher {
  _ToStringMatcher(matcher) : super("Object toString value", "toString", matcher);
  @override
  String featureValueOf(dynamic actual) => actual.toString();
}
```

**Comment by sturmf** [comment]
Another update, I now figured out that the expect implementation actually makes the code break. If I regularly catch the exception I can continue to login as alice. So now I wonder what is wrong with the expect?

My current working implementation is this, but it is really ugly:
```
try {
  await sailingClubBob.set({"roles": {bob.uid: 'owner'}}, new fs.SetOptions(merge: true));
  expect('Should not be reached', '');
} on fb.FirebaseError catch (e) {
  expect(e.toString(), 'FirebaseError: [code=permission-denied]: Missing or insufficient permissions.');
}
```

**Comment by sturmf** [comment]
Ahh damnit, finally figured it out. The expect with an async function returns immediately which of course collides with the next executed line where I relogin.
he solution is to use `await expectLater`

**Comment by kevmoo** [comment]
Sounds like you figured it out, @sturmf – closing
