### ISSUE TITLE
Can't use firebase-dart on standalone VM

### ISSUE THREAD

**Issue by amirh** [firebase/firebase-dart#161]
Just by importing `package:firebase/firebase.dart` and running the file on the standalone Dart VM I get:

```
The built-in library 'dart:js' is not available on the stand-alone VM.
'package:js/js.dart': error: line 8 pos 1: library handler failed
export 'dart:js' show allowInterop, allowInteropCaptureThis;
^
```

**Comment by kevmoo** [comment]
We need to update the documentation here.

For stand-alone VM, you have to use `package:firebase/firebase_io.dart`

**Comment by kevmoo** [comment]
FYI – updated the REAME to be a bit more clear - https://github.com/firebase/firebase-dart
