### ISSUE TITLE
Wrapping firebase's new auth's

### ISSUE THREAD

**Issue by rayk** [firebase/firebase-dart#17]
Anyone working on adding wrappings for the new firebase auth calls into the library?

authWithCustomToken(), authWithOAuthPopup(), etc...

**Comment by SatWiz** [comment]
Can you also please implement authAnonymously function. As I understand not to use firebase secret & password in client based applications without an user/password interface.

**Comment by davenotik** [comment]
So, how does one get at the `auth` in the `AuthResponse` object returned by `authWithCustomToken()`?

It's a `JSObject` as per:

```
class AuthResponse {
  final int expires;
  final JsObject auth;

  AuthResponse(JsObject response)
      : expires = response['expires'],
        auth = response['auth'];

  String toString() => 'expires: $expires, auth: $auth';
}
```

My current attempt, but prints nulls:

```
    f.authWithCustomToken(app.authToken).then((AuthResponse res) {
      JsObject obj = res.auth;
      print(obj['auth']);
    }).catchError((error) => print(error));
```

**Comment by rayk** [comment]
Hi Dave...

```dart
f.authWithCustomToken(app.authToken).then((AuthResponse res){
   print(res.int) ///// milsSinceEpochExpireTime
   print(res.auth['auth']) /// should give you the auth token payload///

what is not in there is uid and provider.....

})........

**Comment by almstrand** [comment]
Does this work? 
```
f.authWithCustomToken(app.authToken).then((AuthResponse res) {
  JsObject obj = res.auth;
  print("uid:${obj['uid']}, provider:${obj['provider']}, expires:${res.expires}");
}).catchError((error) => print(error));
```

**Comment by madisona** [comment]
I've added pull requests for most of these. I've wrapped authAnonymously, authWithOAuthPopup, authWithOAuthRedirect, getAuth, and onAuth. If anyone has advice on tests/better tests I'd love to hear it. 

getAuth has already been merged, the others are in the pull request queue. I'll create an issue for some of the other auth related methods that still aren't present. (changeEmail, changePassword, resetPassword)

**Comment by davenotik** [comment]
@almstrand that does indeed! I get a return like:

`uid:dave, provider:null, expires:1457534242495`

Thank you. `getAuth()` will be helpful too. Thanks for the great work. I'm glad to see this lib getting love.

**Comment by sethladd** [comment]
I've merged 3 of the 4 PRs from @madisona . When we merge the last one, will we be able to close this?

**Comment by sethladd** [comment]
I've merged the final PR from @madisona . Can we close this?

**Comment by sethladd** [comment]
Closing and will reopen if someone asks me to :)
