### ISSUE TITLE
Error in RTDB update call from dart2js build

### ISSUE THREAD

**Issue by montyr75** [firebase/firebase-dart#173]
```
Uncaught Error: Reference.update failed: First argument  contains an invalid key ($identityHash) in property 'users.temp-UID.orgs.0'.  Keys must be non-empty strings and can't contain ".", "#", "$", "/", "[", or "]"
    at validation.js:139
    at Object.t.forEach (obj.js:37)
    at Object.t.validateFirebaseData (validation.js:132)
    at validation.js:149
    at Object.t.forEach (obj.js:37)
    at Object.t.validateFirebaseData (validation.js:132)
    at validation.js:223
    at Object.t.forEach (obj.js:37)
    at Object.t.validateFirebaseMergeDataArg (validation.js:221)
    at t.update (Reference.js:131)
```

This error occurs when calling `update()` with a somewhat complex JSON structure. I have created a minimal project that reproduces the error here: https://github.com/montyr75/test_dart

The test project attempts to update an existing user record in the test database I created but when run from a release build, it fails with the above error.

The project uses Dart 1.24.3 and firebase 4.4.0. The problem started happening with changes in version 4.3.0, however. I ran the tests on Windows 10.

The exception does _not_ occur when running in Dartium. It only occurs when running from a dart2js release build in Chrome (not sure if it happens in a debug build).

For some reason, a property containing an illegal character, `$identityHash`, seems to end up in the JS object that is passed to Firebase.

**Comment by kevmoo** [comment]
Seeing it locally – digging in...

**Comment by kevmoo** [comment]
@montyr75 – so this is fixed, but it's mixed in with fixes that require Dart 2.

Are you in a place where you are looking to migrate to Dart 2?

**Comment by montyr75** [comment]
Yes! In fact, on my company's primary AngularDart project, this was one of the key issues preventing the migration. Thanks, @kevmoo.

**Comment by kevmoo** [comment]
v4.5.0 is out w/ the fix for this issue - https://pub.dartlang.org/packages/firebase
