### ISSUE TITLE
Cannot find native JavaScript type (firebase.Thenable) for type check

### ISSUE THREAD

**Issue by afpatmin** [firebase/firebase-dart#177]
When calling `update(<String, String>{'key':'value'})` on a (valid) DocumentReference using DDC i get a warning: `Cannot find native JavaScript type (firebase.Thenable) for type check`

The same call crashes when compiled to javascript

Dart VM version: 2.0.0-dev.61.0 (Unknown timestamp) on "linux_x64"

  firebase:
    dependency: "direct main"
    description:
      name: firebase
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.5.0"

**Comment by afpatmin** [comment]
I created a minimal repro here: [https://github.com/afpatmin/firebase_issue_repro](https://github.com/afpatmin/firebase_issue_repro)

**Comment by kevmoo** [comment]
Root cause: https://github.com/dart-lang/sdk/issues/33537

**Comment by kevmoo** [comment]
Actually @afpatmin I found out the issue w/ the warning print out with DDC - separate issue from the crash.

Fixed here https://github.com/firebase/firebase-dart/commit/8ec1f4bf8d139c2361f2014ef211ae3e8037c3f3
