### ISSUE TITLE
auth.dart:73 Cannot find native JavaScript type (firebase.UserInfo) for type check

### ISSUE THREAD

**Issue by rich-j** [firebase/firebase-dart#182]
In Chrome we now get the warning:

    auth.dart:73 Cannot find native JavaScript type (firebase.UserInfo) for type check

when we get the user's providerData

    static AuthProvider firebaseProvider2AuthProvider(fb.User firebaseUser) {
      // Firebase providerData is an array that lists in order the providers used to signin - the first one is most recent
      final providerId = firebaseUser.providerData.first?.providerId;    // Note that firebaseUser.providerId just returns "firebase"
      ...

Running:
  firebase 5.0.0-beta
  Dart VM version: 2.0.0-dev.66.0 (Fri Jun 29 11:19:05 2018 +0200) on "macos_x64"

This seems similar to closed issue https://github.com/firebase/firebase-dart/issues/179

**Comment by kevmoo** [comment]
That's an easy fix, too. Just need to add 'anonymous' annotation to that
type.
