### ISSUE TITLE
Version 5.0.1 breaks project. Error when calling firestore onSnapshot.listen

### ISSUE THREAD

**Issue by jmnyv** [firebase/firebase-dart#193]
When calling...

```
fs.collection("col").doc("coc").onSnapshot.listen((doc) {
  ...
}
```

I get

> EXCEPTION: FirebaseError: [code=invalid-argument]: Unknown option 'timestampsInSnapshots' passed to function settings(). Available options: host, ssl, credentials

...despite "timestampsInSnapshots" existing absolutely nowhere in my code. I've tried using null and empty settings objects (`fb.firestore().settings(new Settings()) `) with the same result.

Dart VM version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "macos_x64"
angular: 5.0.0
firebase: 5.0.1

**Comment by jmnyv** [comment]
My bad. Solution: upgrade the javascript app.

<script src="https://www.gstatic.com/firebasejs/5.3.0/firebase.js">

**Comment by kevmoo** [comment]
Which version of the firebase JS libraries are you using? Are you using
5.1.0 as described here? https://pub.dartlang.org/packages/firebase

**Comment by jmnyv** [comment]
@kevmoo That was indeed the issue. Please see my comment further up. My bad.

**Comment by kevmoo** [comment]
Glad you figured it out, @jmnyv !
