### ISSUE TITLE
Tests fail with user credentials

### ISSUE THREAD

**Issue by fusion44** [firebase/firebase-dart#23]
Hi,

I've wrapped getAuth() and want to create a test for it. Unfortunately, when I use my Firebase URL and email address for the tests, they run but crash at some point. I don't know where exactly the crash occurs as it doesn't seem to be in a part that isn't accessible to me. I can see on my dashboard that the user is actually created.

Here's the message I get:
>FIREBASE WARNING: set at /2015-02-01T17:36:37_923Z failed: permission_denied  (https://cdn.firebase.com/js/client/1.1.2/firebase.js:42)
>Breaking on exception: Closure call with mismatched arguments: function 'call'

I've not changed or added any test yet, only added my credentials. Any idea what may cause this?

**Comment by sethladd** [comment]
We just merged a bunch of changes. Maybe try the latest from Github?

**Comment by fusion44** [comment]
Ok, thanks. I'll try this after next week when I return from vacation.

**Comment by kevmoo** [comment]
I think this is addressed...
