### ISSUE TITLE
Needs additional Auth Methods (changeEmail, changePassword, resetPassword)

### ISSUE THREAD

**Issue by madisona** [firebase/firebase-dart#35]
There are three auth related methods still missing from the Dart API.

    changeEmail()
    changePassword()
    resetPassword()

https://www.firebase.com/docs/web/api/firebase/changeemail.html
https://www.firebase.com/docs/web/api/firebase/changepassword.html
https://www.firebase.com/docs/web/api/firebase/resetpassword.html

**Comment by Aza1** [comment]
Its weird (quite misleading to new users) that the Introduction on firebase.dart on pub does NOT highlight unsupported APIs of the firebaseJS. 
Could the authors please kindly address this.

**Comment by madisona** [comment]
I've created pull request #36 for the changePassword() and resetPassword() methods. 

changeEmail() will not be available until we can sync up with the firebase api 2.1.0 or higher. (2.2.2 is the current)

**Comment by sethladd** [comment]
#36 has been merged. Thanks!
