### ISSUE TITLE
Firebase 2.2.2

### ISSUE THREAD

**Issue by madisona** [firebase/firebase-dart#38]
Hi @sethladd 

Thanks for your help merging in some of the additional auth methods!  I've got another patch ready that updates this library to be able to use the current firebase 2.2.2 api.  I'll wait on the pull request until the oauth methods hit master so I can hopefully submit it correctly the first time.

After this I think I'm done with my planned updates for a bit. I'm loving firebase & dart together. Thanks for putting up with all the spam.

~ aaron

**Comment by sethladd** [comment]
All your patches are in! Looking forward to updating to 2.2.2

**Comment by alexpaluzzi** [comment]
@madisona Really appreciate the work. Looking awesome.

**Comment by madisona** [comment]
added pull request #39 to add compatibility with api v2.2.2.  Also added the new methods that were introduced since 1.1.2.

**Comment by sethladd** [comment]
Merged! thanks!
