### ISSUE TITLE
Add wrapper for Simple Login

### ISSUE THREAD

**Issue by anantn** [firebase/firebase-dart#4]
It would be cool to also have a wrapper over simple login.

**Comment by almstrand** [comment]
Firebase has deprecated Simple Login: https://www.firebase.com/docs/web/guide/user-auth.html

**Comment by sethladd** [comment]
What do we do with this issue?

@madisona should we close this? did we fix it?

**Comment by madisona** [comment]
@sethladd - Yes, this is resolved. You can now login with any of the ways the simple login allowed, as they are now part of the core features & api.
