### ISSUE TITLE
AuthResponse does not contain full AuthData from Firebase.

### ISSUE THREAD

**Issue by madisona** [firebase/firebase-dart#41]
The `authResponse` object only exposes the `expires` and `auth` items from the `authData` that gets returned from a successful auth or the `getAuth()` method. The `auth` item is insufficient as it only contains the `uid` and `provider`

Each authentication method for Firebase returns much more data, and that data should all be accessible in the `authResponse`.

For example, the `authWithPassword()` authData contains something like this:

    {
        uid: <some-uid>,
        provider: "password",
        token: <firebase-authentication-token>,
        auth: {
            uid: <some-uid>,
            provider: "password"
        },
        expires: <timestamp>,
        password: {
            email: "user@example.com",
            isTemporaryPassword: false
        }
    }

The Google, Facebook, Twitter, Github, and anonymous authentication methods all return their own distinct `authData` elements.
https://www.firebase.com/docs/web/guide/login/google.html
https://www.firebase.com/docs/web/guide/login/facebook.html
https://www.firebase.com/docs/web/guide/login/twitter.html
https://www.firebase.com/docs/web/guide/login/github.html
https://www.firebase.com/docs/web/guide/login/anonymous.html

is there a reason we couldn't or shouldn't expose the raw JsObject? Because each authentication method returns different elements for authData, I don't believe adding all possible items as properties on the AuthResponse object is the right solution.

I'm happy to work on a patch if you give me some direction, but I'm not sure about the history or reasons why it was initially done the way it currently is.

**Comment by madisona** [comment]
There are 5 common items present among all auth methods, `uid`, `provider`, `token`, `expires`, and `auth`.

The other objects would be available based on the provider.  We could create a class that defines each provider type (custom, password, anonymous, facebook, google, twitter, github). In the main AuthResponse object, we could have properties for all these providers and they would all be null except for the provider used. 

Please let me know if there are alternate suggestions. I'll start on my proposal with tests and post back when I have something for review.

**Comment by madisona** [comment]
Here are a couple options:

Option 1: https://gist.github.com/madisona/61b49a392fb0a57fbfd8
An explicit class for each provider type's auth specific data. Access would be property based like:  `auth_response.google.email`

Option 2: https://gist.github.com/madisona/4c1e3fb0d0432d91d891
Each provider type's auth specific data remains a JsObject. Users would need to read Firebase documentation to understand what they will contain. Access would be like: `auth_response['google']['email']`

any thoughts on what is preferable or more generally acceptable?

**Comment by madisona** [comment]
I think the cleanest solution would be to just do what the snapshot.val() method does and turn auth data into JSON and access it in dart like a normal object, no special AuthResponse class.

    var json = context['JSON'].callMethod('stringify', [authData]);
    return JSON.decode(json);

I think this would be the most natural way to access the data. The only thing you'd give up or change would be the toString() method on AuthResponse explicitly returns only the expires and auth values, but even that isn't very pretty because the auth object just shows [object Object].

**Comment by madisona** [comment]
Here is my proposed implemented solution (with tests) if you find it acceptable:  https://github.com/madisona/firebase-dart/commit/e4587d482d5c01a33cd57e33740c0a03fb502ee5

The commit turns an authData object into native dart.  This would be a breaking change as previously you'd access the property `authResponse.auth`  and now that would become just a Map:  `authResponse['auth']`.

If you are ok with the breaking change there, I think it is a clean way to access all the data with a native dart type, not an odd mix of properties that might return a JsObject (like .auth currently does). It also looks better in my opinion without a bunch of extra classes to maintain.

Sorry for not catching this stuff sooner when all the other changes went in.

**Comment by sethladd** [comment]
I'm OK with the breaking change, just bump to 0.5.0.

Please send over the PR with pubspec.yaml and CHANGELOG updated.

Thank you so much!

**Comment by sethladd** [comment]
Merged!
