### ISSUE TITLE
Update startAt() and endAt()

### ISSUE THREAD

**Issue by davenotik** [firebase/firebase-dart#45]
It seems `startAt()` and `endAt()` no longer need named parameters, and in fact the idea of priorities should be divorced from those methods as the newer Firebase Query API lets you start and end based on orderBy_ methods like `orderByPriority` and `orderByChild`.

Relevant code:
https://github.com/firebase/firebase-dart/blob/master/lib/src/firebase.dart#L611-L641

See the newer stuff documented here:
https://www.firebase.com/docs/web/api/query/startat.html
https://www.firebase.com/docs/web/api/query/endat.html

**Comment by davenotik** [comment]
Figured to alert @madisona given all his work upgrading the lib recently. I'm personally not versed in js-interop to be time efficient or I'd do it myself.

**Comment by sethladd** [comment]
Merged in. Thanks to @madisona for the patch.
