### ISSUE TITLE
Add Flutter support

### ISSUE THREAD

**Issue by collinjackson** [firebase/firebase-dart#71]
[Flutter](http://flutter.io) is a new project to help developers build high-performance, high-fidelity, mobile apps for iOS and Android from a single codebase. Flutter developers need the firebase-dart package to add Firebase support to their app.

Here is an example of a Firebase app using Flutter: https://github.com/flutter/firechat-flutter

Mojo is the IPC system that Flutter apps use to call native iOS and Android SDKs. By refactoring firebase-dart into a JavaScript and Mojo backend with a common interface, we can allow the firebase-dart package to work for Flutter developers. We will need https://github.com/dart-lang/sdk/issues/24581 to be fixed before we can do this.

**Comment by kevmoo** [comment]
Waiting on https://github.com/dart-lang/sdk/issues/24581

**Comment by olostan** [comment]
Is this issue is still active as Flutter now use not IPC way of communication with native services?

We really need Firebase in Flutter, and currently dart-lang/sdk#24581 is mostly implemented (only DDC part is left that has no relation to Flutter)

**Comment by collinjackson** [comment]
I closed the pull request since the mojo approach no longer works in Flutter.

I'm not currently working on Firebase database wrappers using the Flutter HostMessages API. I'd love to see these wrappers exist, but I'm not working on them at the moment.

**Comment by mit-mit** [comment]
This is now available here: https://github.com/flutter/plugins/blob/master/FlutterFire.md

**Comment by Janamou** [comment]
@kevmoo can we close this?
