### ISSUE TITLE
Upgrade to 2.4.0

### ISSUE THREAD

**Issue by kasperpeulen** [firebase/firebase-dart#72]
I get errors when trying to run the 2.4.0 version with Dart:

```
FIREBASE WARNING: Exception was thrown by user callback. NoSuchMethodError: method not found: 'call'
Receiver: Closure 'yp'
Arguments: [null, null]
```

I have no idea what it exactly is, but I guess there were breaking changes in 2.4.0.

**Comment by sirctseb** [comment]
It looks like all the onComplete callbacks are being passed a second argument that is null whether there is an error or not. I've only incurred a PERMISSION_DENIED error to test it, so maybe on other errors there is more information passed. The tests pass after `%s/\(err\) \{/(err, _) {/` in lib/src/firebase.dart and lib/src/disconnect.dart, but I don't know what the extra argument is for.

**Comment by kevmoo** [comment]
Done in 6c5552c
