### ISSUE TITLE
Firebase.getDefaultConfig().setPersistenceEnabled(true);

### ISSUE THREAD

**Issue by kasperpeulen** [firebase/firebase-dart#73]
![image](https://cloud.githubusercontent.com/assets/1035299/12888853/5981ad68-ce7c-11e5-9b33-853e5b6e35ea.png)

How do I do that with Dart?

**Comment by kevmoo** [comment]
Looks like we might need a patch to fix this. Pull requests welcome.

**Comment by katowulf** [comment]
Firebase only offers full offline functionality for iOS and Android. See [this talk thread](https://groups.google.com/forum/#!searchin/firebase-talk/javascript$20offline/firebase-talk/GzV6itqYTRw/f99t83sTKycJ) for some ideas about using native offline persistence via cordova.

**Comment by kasperpeulen** [comment]
@katowulf Oh sorry, I didn't see that this was about android. This is actually for some web app (Progressive Web App I guess you could say). 

> The Firebase client automatically keeps a queue of all write operations that are performed while our application is offline. When persistence is enabled, this queue will also be persisted to disk so all of our writes will be available when we restart the app. When the app regains connectivity, all of the operations will be sent to the server.

I thought with enabling this, the queue would be persisted to local storage or something.
