### ISSUE TITLE
Update the library to support the newly-introduced 3.x Firebase SDKs

### ISSUE THREAD

**Issue by jsayol** [firebase/firebase-dart#79]
Is anyone working on it?

Docs: https://firebase.google.com/docs/

**Comment by montyr75** [comment]
Yes, we need this very badly.

**Comment by kevmoo** [comment]
I've been helping with the Dart Firebase library – but purely as a side project.

If a community member wants to take a stab here, I would be happy to support them.

**Comment by lejard-h** [comment]
There is 2 others firebase library with native implementation

https://pub.dartlang.org/packages/firebase_rest
https://pub.dartlang.org/packages/firebase_dart

I don't know if they are compatible with the last version and I never used them, but both library have been update recently.

It could be a good thing to unify all those package in only one package.

**Comment by jsayol** [comment]
> If a community member wants to take a stab here, I would be happy to support them.

Thanks @kevmoo, that was my intention when I opened this issue. I just realized it might have come off as demanding instead, my bad :)

> There is 2 others firebase library with native implementation
> 
> https://pub.dartlang.org/packages/firebase_rest
> https://pub.dartlang.org/packages/firebase_dart

@lejard-h both those libraries seem to be using the old API

I've been looking around but I've only been able to find the minified/obscured version of the JS library (https://www.gstatic.com/firebasejs/3.0.4/firebase.js). Does anyone know if Firebase has published the source for it, or if they're willing to? If so, [we might be able to use a tool such as this](https://github.com/dart-lang/sdk/issues/24874) whenever it's available. Or, even better, use the [ts2dart transpiler from the Angular team](https://github.com/angular/ts2dart) to generate native Dart code. I'm not sure how well it handles Promises or WebSockets but it'd be worth a try.

If the only option is to work with the published, minified version of the library then there's going to be a lot of work to do.

**Comment by Linkmaster08** [comment]
> If the only option is to work with the published, minified version of the library then there's going to be a lot of work to do.

May it be a possibility to use the Firebase REST Interface directly? Someone could create a pure dart implementation with the REST Interface and Server-Sent-Events(SSE) from Firebase. 

https://firebase.google.com/docs/reference/rest/database/#section-get

The only problem is the support for SSE in Internet Explore or Edge.
[http://caniuse.com/#feat=eventsource](http://caniuse.com/#feat=eventsource)

**Comment by jsayol** [comment]
> May it be a possibility to use the Firebase REST Interface directly?

AFAIK they only expose the _database_ and _authentication_ APIs over REST, which means we wouldn't be able to access all the new features like storage. It's still an option but let's keep that in mind.

**Comment by Linkmaster08** [comment]
Yaa, that's right, as far as i've seen. But it could be easier for a community driven library to write a pure dart REST Client instead of a JavaScript wrapper for a minified JS Library. 

I think, Google should support Dart at least through it's various web libraries, because not doing this blocks the adoption of this beautiful (IMHO) language completely. 👎 :(

**Comment by kevmoo** [comment]
I just spent a bunch of time on https://github.com/Janamou/firebase3-dart

I'm going to see if we can just make this **the** firebase library.

Stay tuned...

**Comment by kevmoo** [comment]
FYI @Janomou

**Comment by kevmoo** [comment]
FYI @Janamou

**Comment by kevmoo** [comment]
Fixed in 3819fbe7d0611059fbf2c72a0387da84d53399ea
