### ISSUE TITLE
goOnline and goOffline not defined

### ISSUE THREAD

**Issue by sirctseb** [firebase/firebase-dart#81]

**Comment by Janamou** [comment]
@kevmoo is this still relevant?

**Comment by kevmoo** [comment]
@Janamou Not sure. Are these implemented? Do they existing in v3?

**Comment by sirctseb** [comment]
They appear to still exist in v3, and are implemented dart-side
https://firebase.google.com/docs/reference/js/firebase.database.Database#goOnline,
https://github.com/firebase/firebase-dart/blob/master/lib/src/database.dart#L42

**Comment by Janamou** [comment]
@kevmoo @sirctseb ;-)
