### ISSUE TITLE
Cannot set messagingSenderId at initializeApp

### ISSUE THREAD

**Issue by rillomas** [firebase/firebase-dart#95]
I wanted to use Firebase Realtime Database in an App Engine webapp, so I went and initialized my firebase account. The Firebase console told me to use the following parameters:
```apiKey: "...",
authDomain: "...",
databaseURL: "...",
storageBucket: "...",
messagingSenderId: "..."
```
However, the current `initializeApp` function does not allow setting the parameter `messagingSenderId`.

**Comment by Janamou** [comment]
Hi @rillomas,
the messagingSenderId is not yet there because this library doesn't actually have the Firebase cloud messaging implemented (I am planning to look at that soon ;-)).

Do you need to use the messaging interface or this parameter is the only thing you need for now?

Thanks

**Comment by rillomas** [comment]
Hi @Janamou,
Actually I'm not quite sure what I need (or don't need) to get started with Firebase's Realtime Databse.
Is it possible to just ignore the `messagingSenderId` parameter for the time being?
If so that would be fine for me.

**Comment by Janamou** [comment]
@rillomas yep, for the realtime database, the messagingSenderId is not needed.

**Comment by rillomas** [comment]
@Janamou Thanks! I'll see what I can do without it. Though I'll be trying to do something close to https://cloud.google.com/solutions/using-firebase-real-time-events-app-engine so I may need messaging sooner or later...

**Comment by Janamou** [comment]
@rillomas It seems that `firebase.messaging()` is not used in this tutorial so it should be ok for now ;-)

**Comment by Kleak** [comment]
You  can now add messagingSenderId even if you don't need it in the codelabs.
@kevmoo i think this one can now be closed

**Comment by kevmoo** [comment]
Indeed! cheers.
