### ISSUE TITLE
Wrong return types for addScope/setCustomParameters in AuthProviders

### ISSUE THREAD

**Issue by marcojakob** [firebase/firebase-dart#99]
When I use the `addScope` method of `GithubAuthProvider` I get the following error:

```
Return value for method: addScope is JSObjectImpl which is inconsistent with all typed JS interop definitions for method addScope.
EXCEPTION: type 'JSObjectImpl' is not a subtype of type 'void' of 'function result' where
  JSObjectImpl is from dart:js

STACKTRACE: 
package:firebase/src/auth.dart 368:43                         GithubAuthProvider.addScope
```

see https://github.com/firebase/firebase-dart/blob/master/lib/src/interop/auth_interop.dart#L76

* dart version: 1.22.1 on "windows_x64"
* firebase-dart version: 3.0.1
* included firebase-js version: 3.7.8

I guess that the method `addScope` returns another `GithubAuthProvider` instead of void on the JavaScript side (to allow fluent calls). The same might be true for `setCustomParameters`.

I tried fixing it with my own custom implementation of `GithubAuthProviderJsImpl` but wasn't able to completely succeed. Is there something else needed than replacing the `void` return types with `GithubAuthProviderJsImpl`?

**Comment by marcojakob** [comment]
Ok, I found the solution:

## `GithubAuthProvider`

```
class GithubAuthProvider extends AuthProvider<GithubAuthProviderJsImpl> {
  // Other methods omitted...

  void addScope(String scope) => 
      new GithubAuthProvider.fromJsObject(jsObject.addScope(scope));

  void setCustomParameters(Map<String, dynamic> customOAuthParameters) =>
      new GithubAuthProvider.fromJsObject(
          jsObject.setCustomParameters(jsify(customOAuthParameters)));
}
```

## `GithubAuthProvider`

```
@JS('GithubAuthProvider')
class GithubAuthProviderJsImpl extends AuthProviderJsImpl {
  // Other methods omitted ...
  external GithubAuthProviderJsImpl addScope(String scope);
  external GithubAuthProviderJsImpl setCustomParameters(customOAuthParameters);
}
```

**Note:** The same might be needed for the Facebook, Google, and Twitter auth providers.

**Comment by Janamou** [comment]
Hi @marcojakob,
thanks for the report! I will take a look.
